<?php

namespace PancakeBundle\Repository;

/**
 * drawingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class drawingRepository extends \Doctrine\ORM\EntityRepository
{
}
