<?php

namespace PancakeBundle\Repository;

/**
 * otherRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class otherRepository extends \Doctrine\ORM\EntityRepository
{
}
