<?php

namespace PancakeBundle\Repository;

/**
 * textRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class textRepository extends \Doctrine\ORM\EntityRepository
{
}
